export const db = 'infohell-db'
export const questionCollection = 'questions'
export const answerCollection = 'answers'
export const commentCollection = 'comments'
export const voteCollection = 'votes'
export const questionAttachmentCollection = 'question-attachments'